repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  
  # The default branch for the repository
  default_branch: main
  
  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true
  
  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true
  
  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true
  
  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true
  
  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings
    protection:
      # Required status checks
      required_status_checks:
        # Require branches to be up to date before merging
        strict: true
        # Status checks that are required
        contexts: ['Test FTS5 Search Implementation', 'Lint Code']
      
      # Require a pull request before merging
      required_pull_request_reviews:
        # The number of approvals required
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed
        dismiss_stale_reviews: true
      
      # Restrict who can push to the branch
      restrictions: null
