image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - .pytest_cache/

stages:
  - quality
  - test
  - benchmark

code_quality:
  stage: quality
  script:
    - pip install black flake8 isort mypy
    - black . --check --diff
    - isort . --check --diff
    - flake8 . --max-line-length=100
    - mypy . --ignore-missing-imports

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov pytest-xdist
    - pytest tests/ -v -n auto --cov=. --cov-report=xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

benchmark:
  stage: benchmark
  script:
    - pip install -r requirements.txt
    - pip install pytest-benchmark
    - pytest tests/ --benchmark-only
  only:
    - main
