services:
  - type: web
    name: kern-resources
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "kern_resources.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health
    plan: free  # Specify the plan type
    region: oregon  # US West region, closest to California
    autoDeploy: true  # Enable automatic deployments
