services:
  - type: web
    name: kern-resources
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn kern_resources.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    plan: free
    region: oregon
    autoDeploy: true
    buildFilter:
      paths:
        - requirements.txt
        - kern_resources/**
      ignoredPaths:
        - Dockerfile.old
        - docker-compose.yml
