# LiteLLM Proxy Configuration

# General settings
general:
  host: 0.0.0.0
  port: 8000
  environment: development  # development, production
  database_url: sqlite:///token_tracker.db  # SQLite for development

# Model list
model_list:
  # OpenAI models
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: ${OPENAI_API_KEY}

  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: ${OPENAI_API_KEY}

  # Anthropic models
  - model_name: claude-3-haiku
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: ${ANTHROPIC_API_KEY}

  - model_name: claude-3-sonnet
    litellm_params:
      model: claude-3-sonnet-20240229
      api_key: ${ANTHROPIC_API_KEY}

  # GroqCloud models
  - model_name: llama-4-scout
    litellm_params:
      model: meta-llama/llama-4-scout-17b-16e-instruct
      api_key: ${GROQ_API_KEY}

  - model_name: llama-4-scout-8b
    litellm_params:
      model: meta-llama/llama-4-scout-8b-16e-instruct
      api_key: ${GROQ_API_KEY}

# Rate limits
rate_limits:
  # OpenAI models
  - model: gpt-3.5-turbo
    limit: 10
    period: minute

  - model: gpt-4
    limit: 5
    period: minute

  # Anthropic models
  - model: claude-3-haiku
    limit: 10
    period: minute

  - model: claude-3-sonnet
    limit: 5
    period: minute

  # GroqCloud models
  - model: llama-4-scout
    limit: 10
    period: minute

  - model: llama-4-scout-8b
    limit: 15
    period: minute

# Budget settings
budget:
  total: 100.00  # Total budget in USD
  daily: 10.00   # Daily budget in USD
  alerts:
    - threshold: 50  # Alert when 50% of budget is used
      email: erik.jacobs@gmail.com
    - threshold: 80  # Alert when 80% of budget is used
      email: erik.jacobs@gmail.com
    - threshold: 95  # Alert when 95% of budget is used
      email: erik.jacobs@gmail.com

# Cost per token (in USD per 1000 tokens)
costs:
  # OpenAI models
  gpt-3.5-turbo:
    input: 0.0005
    output: 0.0015

  gpt-4:
    input: 0.03
    output: 0.06

  # Anthropic models
  claude-3-haiku:
    input: 0.00025
    output: 0.00125

  claude-3-sonnet:
    input: 0.003
    output: 0.015

  # GroqCloud models
  llama-4-scout:
    input: 0.00011
    output: 0.00034

  llama-4-scout-8b:
    input: 0.00008
    output: 0.00024

# Logging settings
logging:
  level: INFO
  file: logs/proxy.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 10485760  # 10 MB
  backup_count: 5
