name: Test FTS5 Search Implementation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'fts_search_api.py'
      - 'setup_fts_index.py'
      - 'tests/test_fts_search.py'
      - '.github/workflows/test-fts-search.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests pytest
    
    - name: Create test database
      run: |
        python tests/test_fts_search.py
    
    - name: Run tests
      run: |
        python -m unittest tests.test_fts_search
    
    - name: Check if FTS5 search API starts
      run: |
        python fts_search_api.py &
        sleep 5
        curl http://localhost:8082/
        kill $!
